// ==========================================================================
// BARBERIA_PRO - Mock Database Seed (Bogotá Pilot & Multitenancy)
// Real-world Pilot Data for Bogotá, Colombia
// ==========================================================================

import { Business, BarberProfile, Service, StyleMemory, MultidimensionalFeedback, StyleCatalogItem, LookbookItem } from '../core/types';

export const INITIAL_BUSINESSES: Business[] = [
  // --- TENANT PILOTO REAL 1: ARIZSHOP BARBER ---
  {
    id: 'biz_arizshop_01',
    slug: 'arizshop-barber',
    name: 'ARIZSHOP BARBER',
    slogan: 'Elegancia, precisión y estilo clásico.',
    logoUrl: '/logos/arizshop-logo.jpg',
    bannerUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=1200&h=400&q=80',
    businessType: 'barbershop',
    enabledCategories: ['Corte Clásico', 'Barba & Perfilado', 'Combos'],
    address: 'Pendiente de configuración',
    city: 'Bogotá',
    neighborhood: '',
    phone: '+57 310 236 5163',
    whatsapp: '+57 310 236 5163',
    instagramUrl: '',
    ownerName: 'Álvaro Ortiz',
    ownerPhone: '+57 310 236 5163',
    theme: {
      primary: '#eab308',       // Dorado elegante / Oro Barbería
      primaryHover: '#ca8a04',  // Dorado oscuro para botones
      primaryLight: 'rgba(234, 179, 8, 0.15)', // Tinte dorado de baja opacidad
      accent: '#fbbf24',        // Ámbar brillante
      surface: '#09090b',       // Negro profundo premium
      surfaceCard: '#18181b',   // Zinc 900
      border: '#27272a',        // Borde sutil zinc
      radius: '14px',
      fontHeading: 'Outfit',
      fontBody: 'Plus Jakarta Sans',
    },
    schedules: [
      { dayOfWeek: 1, openTime: '08:00', closeTime: '20:00', isOpen: true },
      { dayOfWeek: 2, openTime: '08:00', closeTime: '20:00', isOpen: true },
      { dayOfWeek: 3, openTime: '08:00', closeTime: '20:00', isOpen: true },
      { dayOfWeek: 4, openTime: '08:00', closeTime: '20:00', isOpen: true },
      { dayOfWeek: 5, openTime: '08:00', closeTime: '21:00', isOpen: true },
      { dayOfWeek: 6, openTime: '08:00', closeTime: '21:00', isOpen: true },
      { dayOfWeek: 0, openTime: '09:00', closeTime: '18:00', isOpen: false },
    ],
    loyalty: {
      type: 'stamps',
      stampsThreshold: 6,
      rewardDescription: '1 Corte de Cabello Completamente Gratis',
      pointsPerPeso: 0,
      birthdayDiscountPercent: 20,
    },
    subscription: {
      status: 'trial_active',
      planId: 'plan_pro',
      trialStartedAt: '2026-08-18T10:00:00Z',
      trialEndsAt: '2026-08-25T10:00:00Z',
      currentPeriodEnd: '2026-08-25T10:00:00Z',
      cancelAtPeriodEnd: false,
    },
    isVerified: true,
    createdAt: '2026-08-18T10:00:00Z',
  },
  // --- TENANT DESARROLLO 2: El Parche Barber Studio ---
  {
    id: 'biz_el_parche_01',
    slug: 'el-parche',
    name: 'El Parche Barber Studio',
    slogan: 'Tu corte, tu estilo, tu espacio.',
    logoUrl: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&w=200&h=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=1200&h=400&q=80',
    businessType: 'barbershop',
    enabledCategories: ['Caballero', 'Barba', 'Combos', 'Tratamientos', 'Niños'],
    address: 'Calle 67 # 9-24, Chapinero',
    city: 'Bogotá',
    neighborhood: 'Chapinero Alto',
    phone: '+57 312 456 7890',
    whatsapp: '+57 312 456 7890',
    instagramUrl: 'https://instagram.com/elparchebarber',
    ownerName: 'Carlos Mendoza',
    ownerEmail: 'carlos@elparchebarber.co',
    theme: {
      primary: '#f59e0b',       // Ámbar dorado premium
      primaryHover: '#d97706',
      primaryLight: 'rgba(245, 158, 11, 0.15)',
      accent: '#38bdf8',        // Azul cielo
      surface: '#121214',
      surfaceCard: '#1f1f23',
      border: '#2e2e33',
      radius: '16px',
      fontHeading: 'Outfit',
      fontBody: 'Plus Jakarta Sans',
    },
    schedules: [
      { dayOfWeek: 1, openTime: '08:00', closeTime: '20:00', isOpen: true },
      { dayOfWeek: 2, openTime: '08:00', closeTime: '20:00', isOpen: true },
      { dayOfWeek: 3, openTime: '08:00', closeTime: '20:00', isOpen: true },
      { dayOfWeek: 4, openTime: '08:00', closeTime: '20:00', isOpen: true },
      { dayOfWeek: 5, openTime: '08:00', closeTime: '21:00', isOpen: true },
      { dayOfWeek: 6, openTime: '08:00', closeTime: '21:00', isOpen: true },
      { dayOfWeek: 0, openTime: '09:00', closeTime: '18:00', isOpen: true },
    ],
    loyalty: {
      type: 'stamps',
      stampsThreshold: 8,
      rewardDescription: '1 Corte de cabello Master gratis',
      pointsPerPeso: 0,
      birthdayDiscountPercent: 25,
    },
    subscription: {
      status: 'trial_active',
      planId: 'plan_pro',
      trialStartedAt: '2026-08-15T10:00:00Z',
      trialEndsAt: '2026-08-22T10:00:00Z',
      currentPeriodEnd: '2026-08-22T10:00:00Z',
      cancelAtPeriodEnd: false,
    },
    isVerified: true,
    createdAt: '2026-08-01T10:00:00Z',
  },
  // --- TENANT DESARROLLO 3: Bogotá Barber Club ---
  {
    id: 'biz_bogota_club_02',
    slug: 'bogota-barber-club',
    name: 'Bogotá Barber Club',
    slogan: 'Tradición y excelencia en cada detalle.',
    logoUrl: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=200&h=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&w=1200&h=400&q=80',
    businessType: 'studio',
    enabledCategories: ['Corte Clásico', 'Ritual de Barba', 'Spa Facial', 'Exclusivos'],
    address: 'Carrera 7 # 116-50, Usaquén',
    city: 'Bogotá',
    neighborhood: 'Santa Bárbara / Usaquén',
    phone: '+57 301 987 6543',
    whatsapp: '+57 301 987 6543',
    instagramUrl: 'https://instagram.com/bogotabarberclub',
    theme: {
      primary: '#10b981',       // Verde Esmeralda Colombiana
      primaryHover: '#059669',
      primaryLight: 'rgba(16, 185, 129, 0.15)',
      accent: '#eab308',        // Dorado
      surface: '#0f172a',       // Azul pizarra muy oscuro
      surfaceCard: '#1e293b',
      border: '#334155',
      radius: '12px',
      fontHeading: 'Outfit',
      fontBody: 'Plus Jakarta Sans',
    },
    schedules: [
      { dayOfWeek: 1, openTime: '09:00', closeTime: '19:00', isOpen: true },
      { dayOfWeek: 2, openTime: '09:00', closeTime: '19:00', isOpen: true },
      { dayOfWeek: 3, openTime: '09:00', closeTime: '19:00', isOpen: true },
      { dayOfWeek: 4, openTime: '09:00', closeTime: '20:00', isOpen: true },
      { dayOfWeek: 5, openTime: '09:00', closeTime: '20:00', isOpen: true },
      { dayOfWeek: 6, openTime: '08:00', closeTime: '19:00', isOpen: true },
      { dayOfWeek: 0, openTime: '10:00', closeTime: '16:00', isOpen: false },
    ],
    loyalty: {
      type: 'points',
      stampsThreshold: 10,
      rewardDescription: 'Ritual de Barba con Toalla Caliente Gratis',
      pointsPerPeso: 0.05,
      birthdayDiscountPercent: 20,
    },
    subscription: {
      status: 'active',
      planId: 'plan_enterprise',
      trialStartedAt: '2026-07-01T00:00:00Z',
      trialEndsAt: '2026-07-08T00:00:00Z',
      currentPeriodEnd: '2026-09-01T00:00:00Z',
      cancelAtPeriodEnd: false,
    },
    isVerified: true,
    createdAt: '2026-07-01T10:00:00Z',
  }
];

export const INITIAL_BARBERS: BarberProfile[] = [
  // --- TENANT 1: ARIZSHOP BARBER ---
  {
    id: 'barber_arizshop_alvaro',
    businessId: 'biz_arizshop_01',
    fullName: 'Álvaro Ortiz (Fundador & Maestro Barbero)',
    role: 'barber',
    phone: '+57 310 236 5163',
    commissionPercentage: 50,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&h=200&q=80',
    specialties: ['Corte Clásico Premium', 'Perfilado de Barba', 'Asesoría de Imagen'],
    bio: 'Atención personalizada y precisión en barbería clásica y moderna en Bogotá.',
    ratingAverage: 5.0,
    happyClientsPct: 100,
    totalCutsCompleted: 0,
    isActive: true,
    createdAt: '2026-08-18T10:00:00Z',
  },
  {
    id: 'barber_arizshop_daniel',
    businessId: 'biz_arizshop_01',
    fullName: 'Daniel Sánchez (Especialista en Fades & Diseños)',
    role: 'barber',
    phone: '+57 312 456 7890',
    commissionPercentage: 50,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&h=200&q=80',
    specialties: ['Skin Fade', 'Taper Fade', 'Diseños Freestyle', 'Texturizado'],
    bio: 'Especialista en degradados milimétricos y estilos urbanos de alta definición.',
    ratingAverage: 5.0,
    happyClientsPct: 100,
    totalCutsCompleted: 0,
    isActive: true,
    createdAt: '2026-08-18T10:00:00Z',
  },
  // --- TENANT 2: El Parche Barber Studio ---
  {
    id: 'barber_camilo_01',
    businessId: 'biz_el_parche_01',
    fullName: 'Camilo "El Flaco" Restrepo',
    role: 'barber',
    phone: '+57 312 111 2233',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&h=200&q=80',
    specialties: ['Mid Fade', 'Skin Fade', 'Diseño de Barba', 'Texturizado'],
    bio: 'Especialista en degradados modernos y asesoría de imagen. 6 años de experiencia.',
    ratingAverage: 4.9,
    happyClientsPct: 98,
    totalCutsCompleted: 420,
    isActive: true,
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'barber_mateo_02',
    businessId: 'biz_el_parche_01',
    fullName: 'Mateo Rodríguez',
    role: 'barber',
    phone: '+57 315 222 3344',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&h=200&q=80',
    specialties: ['Tijera Clásica', 'Pompadour', 'Perfilado Navaja', 'Cuidado Capilar'],
    bio: 'Maestro de la tijera y cortes ejecutivos impecables.',
    ratingAverage: 4.8,
    happyClientsPct: 95,
    totalCutsCompleted: 310,
    isActive: true,
    createdAt: '2026-08-01T10:00:00Z',
  },
  // --- TENANT 3: Bogotá Barber Club ---
  {
    id: 'barber_andres_03',
    businessId: 'biz_bogota_club_02',
    fullName: 'Andrés Silva (Maestro Barbero)',
    role: 'barber',
    phone: '+57 301 333 4455',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&h=200&q=80',
    specialties: ['Corte Caballero Tradicional', 'Ritual de Barba con Toalla', 'Afeitado Clásico'],
    bio: '12 años de trayectoria en barbería clásica europea y alta peluquería en Usaquén.',
    ratingAverage: 5.0,
    happyClientsPct: 100,
    totalCutsCompleted: 650,
    isActive: true,
    createdAt: '2026-07-01T10:00:00Z',
  }
];

export const INITIAL_SERVICES: Service[] = [
  // --- TENANT 1: ARIZSHOP BARBER ---
  {
    id: 'srv_arizshop_corte',
    businessId: 'biz_arizshop_01',
    name: 'Corte Clásico & Fade Pro',
    description: 'Lavado, asesoría de estilo personalizada, corte a máquina y tijera, peinado final.',
    category: 'Corte Clásico',
    priceCOP: 38000,
    durationMinutes: 45,
    isPopular: true,
    isActive: true,
  },
  {
    id: 'srv_arizshop_barba',
    businessId: 'biz_arizshop_01',
    name: 'Perfilado de Barba & Ritual Toalla Caliente',
    description: 'Vaporizador / toalla caliente, perfilado con navaja milimétrico y bálsamo hidratante.',
    category: 'Barba & Perfilado',
    priceCOP: 25000,
    durationMinutes: 30,
    isPopular: true,
    isActive: true,
  },
  {
    id: 'srv_arizshop_combo',
    businessId: 'biz_arizshop_01',
    name: 'Combo Master (Corte + Barba + Estilizado)',
    description: 'Experiencia completa de corte y cuidado de barba en una sola sesión.',
    category: 'Combos',
    priceCOP: 55000,
    durationMinutes: 60,
    isPopular: true,
    isActive: true,
  },
  // --- TENANT 1: El Parche Barber Studio ---
  {
    id: 'srv_corte_parche',
    businessId: 'biz_el_parche_01',
    name: 'Corte Master Personalizado',
    description: 'Lavado premium, asesoría de estilo, corte a máquina y tijera, terminación con navaja y peinado.',
    category: 'Caballero',
    priceCOP: 35000,
    durationMinutes: 45,
    isPopular: true,
    isActive: true,
  },
  {
    id: 'srv_combo_parche',
    businessId: 'biz_el_parche_01',
    name: 'Combo Parche (Corte + Barba)',
    description: 'Corte completo + Ritual de barba con toalla caliente, aceite hidratante y navaja.',
    category: 'Combos',
    priceCOP: 55000,
    durationMinutes: 60,
    isPopular: true,
    isActive: true,
  },
  {
    id: 'srv_barba_parche',
    businessId: 'biz_el_parche_01',
    name: 'Perfilado y Ritual de Barba',
    description: 'Vapor de ozono, toalla caliente, perfilado milimétrico y bálsamo nutritivo.',
    category: 'Barba',
    priceCOP: 25000,
    durationMinutes: 30,
    isPopular: false,
    isActive: true,
  },
  // --- TENANT 2: Bogotá Barber Club ---
  {
    id: 'srv_club_corte_ejecutivo',
    businessId: 'biz_bogota_club_02',
    name: 'Corte Ejecutivo Bogotá Club',
    description: 'Lavado con shampoo de menta y eucalipto, corte a tijera de precisión, peinado con cera mate.',
    category: 'Corte Clásico',
    priceCOP: 48000,
    durationMinutes: 50,
    isPopular: true,
    isActive: true,
  },
  {
    id: 'srv_club_ritual_barba',
    businessId: 'biz_bogota_club_02',
    name: 'Ritual Imperial de Barba',
    description: 'Doble toalla caliente con aceites esenciales, afeitado a navaja tradicional y masaje facial.',
    category: 'Ritual de Barba',
    priceCOP: 38000,
    durationMinutes: 40,
    isPopular: true,
    isActive: true,
  }
];

export const INITIAL_STYLE_MEMORIES: StyleMemory[] = [
  // --- TENANT 2: El Parche Barber Studio (Desarrollo) ---
  {
    id: 'mem_juan_01',
    businessId: 'biz_el_parche_01',
    clientId: 'client_juan_perez',
    barberId: 'barber_camilo_01',
    appointmentId: 'apt_prev_01',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&h=400&q=80',
    likedAspects: ['Degradado medio bien pulido', 'Forma y perfilado de la barba'],
    keepAspects: ['Volumen superior para peinado hacia el lado derecho'],
    changeAspects: ['Dejar un poco más de largo atrás', 'No subir demasiado los laterales'],
    technicalFormula: 'Fade 1.5 a 3 lateral, tijera 3cm arriba texturizada, navaja en contornos',
    customerRemarks: 'El último corte quedó un poco corto atrás en la nuca. Quiere mantener más largo esta vez.',
    consentPhotoGranted: true,
    createdAt: '2026-08-05T15:30:00Z',
  },
  // --- TENANT 2: Bogotá Barber Club ---
  {
    id: 'mem_felipe_02',
    businessId: 'biz_bogota_club_02',
    clientId: 'client_felipe_gomez',
    barberId: 'barber_andres_03',
    appointmentId: 'apt_prev_02',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&h=400&q=80',
    likedAspects: ['Largo a tijera en cúspide', 'Textura natural sin cera brillante'],
    keepAspects: ['Patillas en punta clásica'],
    changeAspects: ['Rebajar un poco más las patillas'],
    technicalFormula: 'Corte clásico tijera sobre peine, terminación natural en cuello',
    customerRemarks: 'Cliente prefiere secado con aire frío.',
    consentPhotoGranted: true,
    createdAt: '2026-08-10T11:00:00Z',
  }
];

export const INITIAL_FEEDBACKS: MultidimensionalFeedback[] = [
  // --- TENANT 2: El Parche Barber Studio ---
  {
    id: 'fb_01',
    businessId: 'biz_el_parche_01',
    appointmentId: 'apt_prev_01',
    clientId: 'client_juan_perez',
    barberId: 'barber_camilo_01',
    ratingCut: 5,
    ratingAttention: 5,
    ratingListening: 5,
    ratingWaitTime: 4,
    ratingOverall: 5,
    likedMostComment: 'Camilo entendió exactamente el estilo que quería y la barba quedó perfecta.',
    improveNextTimeComment: 'Esperé unos 8 minutos antes de pasar a la silla, aunque el café de cortesía estuvo genial.',
    isPrivate: true,
    createdAt: '2026-08-05T16:45:00Z',
  },
  // --- TENANT 2: Bogotá Barber Club ---
  {
    id: 'fb_02',
    businessId: 'biz_bogota_club_02',
    appointmentId: 'apt_prev_02',
    clientId: 'client_felipe_gomez',
    barberId: 'barber_andres_03',
    ratingCut: 5,
    ratingAttention: 5,
    ratingListening: 5,
    ratingWaitTime: 5,
    ratingOverall: 5,
    likedMostComment: 'El ritual de toalla caliente de Andrés es insuperable. Puntualidad británica.',
    improveNextTimeComment: '',
    isPrivate: true,
    createdAt: '2026-08-10T12:00:00Z',
  }
];

export const STYLE_CATALOG_ITEMS: StyleCatalogItem[] = [
  {
    id: 'style_siete_colombiano',
    name: 'El Siete Colombiano (Corte Siete)',
    category: 'corte',
    targetAudience: 'adultos',
    description: 'El corte más representativo de la barbería en Colombia. Fade lateral en V con línea definida a navaja y textura superior.',
    tags: ['Tradicional Colombiano', 'El Siete', 'Líneas', 'Fade', 'Diseño', 'Adultos'],
    previewOverlayUrl: '/styles/el-siete-colombiano.jpg',
    difficultyLevel: 'avanzado',
    hairType: 'todos',
    faceShape: 'Ideal para rostros ovalados y cuadrados. Estiliza el perfil.',
    technicalFormula: 'Laterales en V desde guía 0.5 a 2.5 • Navaja en patilla • Tijera texturizada 3cm arriba',
    angles: { front: '/styles/el-siete-colombiano.jpg', side: '/styles/el-siete-colombiano.jpg', back: '/styles/el-siete-colombiano.jpg' }
  },
  {
    id: 'style_burst_fade',
    name: 'Burst Fade / Mohicano Moderno',
    category: 'corte',
    targetAudience: 'todos',
    description: 'Degradado semicircular alrededor de la oreja con cresta texturizada desde la coronilla hasta la nuca. Muy pedido por niños y jóvenes.',
    tags: ['Burst Fade', 'Mohicano', 'Urbano', 'Textura', 'Niños', 'Diseño'],
    previewOverlayUrl: '/styles/burst-fade.jpg',
    difficultyLevel: 'avanzado',
    hairType: 'afro',
    faceShape: 'Favorece rostros redondos y alargados. Aporta volumen vertical.',
    technicalFormula: 'Degradado semicircular en oreja (0 a 1.5) • Texturizado de cresta con esponja o tijera',
    angles: { front: '/styles/burst-fade.jpg', side: '/styles/burst-fade.jpg', back: '/styles/burst-fade.jpg' }
  },
  {
    id: 'style_mid_fade_crop',
    name: 'Mid Fade + Textured Crop (Infantil & Adulto)',
    category: 'corte',
    targetAudience: 'todos',
    description: 'Degradado a media altura con textura superior desfilada hacia el frente. Fácil de peinar, limpio y el favorito escolar.',
    tags: ['Moderno', 'Fade Medio', 'Textura', 'Juvenil', 'Niños', 'Escolar'],
    previewOverlayUrl: '/styles/mid-fade-crop.jpg',
    difficultyLevel: 'medio',
    hairType: 'liso',
    faceShape: 'Excelente para frentes amplias y rostros angulares.',
    technicalFormula: 'Fade medio a 2 dedos sobre la oreja • Flequillo recto desfilado a tijera dentada',
    angles: { front: '/styles/mid-fade-crop.jpg', side: '/styles/mid-fade-crop.jpg', back: '/styles/mid-fade-crop.jpg' }
  },
  {
    id: 'style_high_skin_fade',
    name: 'High Skin Fade (Degradado Alto a Piel)',
    category: 'corte',
    targetAudience: 'adultos',
    description: 'Degradado alto al ras de navaja en laterales con volumen controlado arriba. Muy fresco, limpio y deportivo.',
    tags: ['Skin Fade', 'Alto', 'Fresco', 'Deportivo', 'Adultos'],
    previewOverlayUrl: '/styles/high-skin-fade.jpg',
    difficultyLevel: 'avanzado',
    hairType: 'todos',
    faceShape: 'Resalta la mandíbula y despeja completamente los laterales.',
    technicalFormula: 'Cero navaja en sienes y nuca alta • Conexión pulida con guía 2 arriba',
    angles: { front: '/styles/high-skin-fade.jpg', side: '/styles/high-skin-fade.jpg', back: '/styles/high-skin-fade.jpg' }
  },
  {
    id: 'style_low_fade_clasico',
    name: 'Low Fade + Peinado Ejecutivo (Side Part / Escolar)',
    category: 'corte',
    targetAudience: 'todos',
    description: 'Degradado bajo elegante a 1cm sobre la oreja con raya al lado. El estándar de elegancia para oficina y colegios.',
    tags: ['Clásico', 'Ejecutivo', 'Low Fade', 'Side Part', 'Escolar', 'Niños'],
    previewOverlayUrl: '/styles/low-fade-executive.jpg',
    difficultyLevel: 'medio',
    hairType: 'liso',
    faceShape: 'Equilibrio perfecto para cualquier tipo de rostro formal.',
    technicalFormula: 'Fade bajo sutil a 1cm de la oreja • Peinado lateral con raya natural a tijera',
    angles: { front: '/styles/low-fade-executive.jpg', side: '/styles/low-fade-executive.jpg', back: '/styles/low-fade-executive.jpg' }
  },
  {
    id: 'style_taper_fade',
    name: 'Taper Fade Natural (Soft Fade con Ondas)',
    category: 'corte',
    targetAudience: 'todos',
    description: 'Desvanecido sutil únicamente en patillas y nuca. Mantiene el largo y rizos naturales tanto en niños como en adultos.',
    tags: ['Taper Fade', 'Soft Fade', 'Natural', 'Conservador', 'Niños', 'Rizos'],
    previewOverlayUrl: '/styles/taper-fade-clean.jpg',
    difficultyLevel: 'medio',
    hairType: 'ondulado',
    faceShape: 'Muy natural para cabello rizado u ondulado con volumen medio.',
    technicalFormula: 'Desvanecido solo en sienes (1cm) y nuca baja • Conservar laterales largos',
    angles: { front: '/styles/taper-fade-clean.jpg', side: '/styles/taper-fade-clean.jpg', back: '/styles/taper-fade-clean.jpg' }
  },
  {
    id: 'style_edgar_crop',
    name: 'Corte Edgar (Honguito Moderno Urbano)',
    category: 'corte',
    targetAudience: 'todos',
    description: 'Flequillo frontal recto marcado con degradado alto lateral. Gran tendencia urbana y juvenil en Colombia.',
    tags: ['Edgar', 'Flequillo Recto', 'Urbano', 'Tendencia', 'Juvenil'],
    previewOverlayUrl: '/styles/corte-edgar.jpg',
    difficultyLevel: 'medio',
    hairType: 'liso',
    faceShape: 'Ideal para rostros jóvenes y fisonomía cuadrada.',
    technicalFormula: 'Línea horizontal recta en frente a tijera • Skin fade alto en costados',
    angles: { front: '/styles/corte-edgar.jpg', side: '/styles/corte-edgar.jpg', back: '/styles/corte-edgar.jpg' }
  },
  {
    id: 'style_pompadour_quiff',
    name: 'Pompadour / Quiff Clásico con Volumen',
    category: 'corte',
    targetAudience: 'adultos',
    description: 'Peinado clásico hacia atrás con gran volumen frontal, laterales pulidos y terminación brillante o mate.',
    tags: ['Pompadour', 'Volumen', 'Tijera', 'Barbería Clásica', 'Adultos'],
    previewOverlayUrl: '/styles/pompadour-quiff.jpg',
    difficultyLevel: 'avanzado',
    hairType: 'liso',
    faceShape: 'Alarga visualmente rostros redondos con altura frontal.',
    technicalFormula: 'Largo superior 8-10cm para cepillado • Laterales cónicos a tijera',
    angles: { front: '/styles/pompadour-quiff.jpg', side: '/styles/pompadour-quiff.jpg', back: '/styles/pompadour-quiff.jpg' }
  },
  {
    id: 'style_buzz_cut_skin',
    name: 'Buzz Cut Militar con Skin Fade (Deportivo)',
    category: 'corte',
    targetAudience: 'todos',
    description: 'Rapado uniforme en la parte superior (guía 2 o 1) con degradado limpio a piel y navaja. Máxima frescura.',
    tags: ['Buzz Cut', 'Rapado Militar', 'Sin Peinar', 'Limpio', 'Deportivo', 'Niños'],
    previewOverlayUrl: '/styles/buzz-cut-skin.jpg',
    difficultyLevel: 'simple',
    hairType: 'todos',
    faceShape: 'Destaca facciones masculinas marcadas y mirada firme.',
    technicalFormula: 'Guía #2 o #1.5 uniforme arriba • Perfilado frontal con navaja',
    angles: { front: '/styles/buzz-cut-skin.jpg', side: '/styles/buzz-cut-skin.jpg', back: '/styles/buzz-cut-skin.jpg' }
  },
  {
    id: 'style_beard_sculpted',
    name: 'Perfilado de Barba & Ritual Toalla Caliente',
    category: 'barba',
    targetAudience: 'adultos',
    description: 'Líneas limpias y milimétricas en pómulos y cuello con navaja tradicional, vapor caliente y bálsamo.',
    tags: ['Barba', 'Perfilado', 'Navaja', 'Toalla Caliente', 'Adultos'],
    previewOverlayUrl: '/styles/perfilado-barba.jpg',
    difficultyLevel: 'medio',
    hairType: 'todos',
    faceShape: 'Define y angula la mandíbula con precisión quirúrgica.',
    technicalFormula: 'Toalla caliente aromatizada • Perfilado con navaja japonesa • Aceite de argán',
    angles: { front: '/styles/perfilado-barba.jpg', side: '/styles/perfilado-barba.jpg', back: '/styles/perfilado-barba.jpg' }
  },
  {
    id: 'style_beard_fade',
    name: 'Beard Fade (Degradado de Barba en Patillas)',
    category: 'barba',
    targetAudience: 'adultos',
    description: 'Transición difuminada que conecta el lateral del corte con la barba para una simetría impecable.',
    tags: ['Degradado Barba', 'Beard Fade', 'Conexión', 'Adultos'],
    previewOverlayUrl: '/styles/beard-fade.jpg',
    difficultyLevel: 'avanzado',
    hairType: 'todos',
    faceShape: 'Conexión suave y estilizada entre rostro y cabello.',
    technicalFormula: 'Degradado inverso desde 0 en la sien hasta densidad total en la mandíbula',
    angles: { front: '/styles/beard-fade.jpg', side: '/styles/beard-fade.jpg', back: '/styles/beard-fade.jpg' }
  },
  {
    id: 'style_combo_imperial',
    name: 'Combo Master Arizshop (Fade + Barba Completa)',
    category: 'combo',
    targetAudience: 'adultos',
    description: 'Servicio insignia de Álvaro Ortiz: Corte personalizado + Spa de barba con toalla caliente y navaja.',
    tags: ['Combo Master', 'Experiencia Completa', 'Álvaro Ortiz', 'Corte + Barba'],
    previewOverlayUrl: '/styles/combo-master.jpg',
    difficultyLevel: 'avanzado',
    hairType: 'todos',
    faceShape: 'Transformación total de imagen adaptada a la anatomía del cliente.',
    technicalFormula: 'Asesoría visagismo + Fade Pro + Ritual de barba con toalla caliente y navaja',
    angles: { front: '/styles/combo-master.jpg', side: '/styles/combo-master.jpg', back: '/styles/combo-master.jpg' }
  },
  {
    id: 'style_french_crop',
    name: 'French Crop con Flequillo Desfilado',
    category: 'corte',
    targetAudience: 'todos',
    description: 'Corte europeo moderno con degradado alto y flequillo corto despuntado. Ideal para bajo mantenimiento diario.',
    tags: ['French Crop', 'Flequillo', 'Textura', 'Bajo Mantenimiento', 'Europeo'],
    previewOverlayUrl: '/lookbook/look_04.jpg',
    difficultyLevel: 'medio',
    hairType: 'liso',
    faceShape: 'Favorece rostros ovalados y frentes amplias.',
    technicalFormula: 'Fade medio-alto a navaja • Texturizado superior con tijera de entresacar',
    angles: { front: '/lookbook/look_04.jpg', side: '/lookbook/look_04.jpg', back: '/lookbook/look_04.jpg' }
  },
  {
    id: 'style_two_block',
    name: 'Two Block Cut (K-Style Moderno)',
    category: 'corte',
    targetAudience: 'todos',
    description: 'Laterales y nuca desvanecidos con desconexión superior más larga y caída natural con raya al medio o al lado.',
    tags: ['Two Block', 'K-Style', 'Desconexión', 'Juvenil', 'Tendencia'],
    previewOverlayUrl: '/lookbook/look_06.jpg',
    difficultyLevel: 'avanzado',
    hairType: 'liso',
    faceShape: 'Ideal para rostros delgados y alargados.',
    technicalFormula: 'Undercut en laterales #2 • Zona superior en capas largas con caída fluida',
    angles: { front: '/lookbook/look_06.jpg', side: '/lookbook/look_06.jpg', back: '/lookbook/look_06.jpg' }
  },
  {
    id: 'style_curly_fade',
    name: 'Fade con Rizos Definidos / Sponge Twist',
    category: 'corte',
    targetAudience: 'todos',
    description: 'Degradado limpio a piel que contrasta con la textura y caída natural de rizos u ondas superiores.',
    tags: ['Rizos', 'Afro', 'Ondas', 'Fade', 'Sponge Twist'],
    previewOverlayUrl: '/lookbook/look_05.jpg',
    difficultyLevel: 'medio',
    hairType: 'afro',
    faceShape: 'Aporta altura y estiliza rostros redondos.',
    technicalFormula: 'Taper fade o Mid fade a navaja • Definición de rizos con crema y esponja',
    angles: { front: '/lookbook/look_05.jpg', side: '/lookbook/look_05.jpg', back: '/lookbook/look_05.jpg' }
  },
  {
    id: 'style_modern_mullet',
    name: 'Modern Mullet + Taper Fade Urbano',
    category: 'corte',
    targetAudience: 'todos',
    description: 'El corte de tendencia global: nuca alargada con textura, laterales pulidos y flequillo desfilado.',
    tags: ['Mullet', 'Moderno', 'Urbano', 'Tendencia', 'Juventud'],
    previewOverlayUrl: '/lookbook/look_18.jpg',
    difficultyLevel: 'avanzado',
    hairType: 'ondulado',
    faceShape: 'Acentúa perfiles atléticos y ángulos faciales.',
    technicalFormula: 'Desvanecido bajo en sienes • Conservar longitud en nuca con capas desconectadas',
    angles: { front: '/lookbook/look_18.jpg', side: '/lookbook/look_18.jpg', back: '/lookbook/look_18.jpg' }
  },
  {
    id: 'style_kids_freestyle',
    name: 'Corte Infantil Deportivo con Línea Freestyle',
    category: 'ninos',
    targetAudience: 'ninos',
    description: 'Degradado fresco y cómodo para niños con línea o rayita artística lateral perfilada a navaja.',
    tags: ['Niños', 'Infantil', 'Línea', 'Freestyle', 'Deportivo', 'Escolar'],
    previewOverlayUrl: '/lookbook/look_09.jpg',
    difficultyLevel: 'medio',
    hairType: 'todos',
    faceShape: 'Muy cómodo y fresco para la rutina escolar y deportiva de los niños.',
    technicalFormula: 'Mid fade suave con máquina • Línea curva sutil lateral con perfilador',
    angles: { front: '/lookbook/look_09.jpg', side: '/lookbook/look_09.jpg', back: '/lookbook/look_09.jpg' }
  },
  {
    id: 'style_viking_beard',
    name: 'Barba Vikinga Esculpida & Aceite Esencial',
    category: 'barba',
    targetAudience: 'adultos',
    description: 'Barba de longitud media/larga con perfilado de mejillas y bigote arreglado, tratada con bálsamo hidratante.',
    tags: ['Barba Vikinga', 'Barba Larga', 'Perfilado', 'Bálsamo', 'Adultos'],
    previewOverlayUrl: '/lookbook/look_11.jpg',
    difficultyLevel: 'medio',
    hairType: 'todos',
    faceShape: 'Alarga visualmente el mentón y da fuerza a la mandíbula.',
    technicalFormula: 'Recorte a tijera para densidad uniforme • Perfilado a navaja en cuello y pómulos',
    angles: { front: '/lookbook/look_11.jpg', side: '/lookbook/look_11.jpg', back: '/lookbook/look_11.jpg' }
  },
  {
    id: 'style_freestyle_design',
    name: 'Diseño Artístico Freestyle en Sillón',
    category: 'disenos',
    targetAudience: 'todos',
    description: 'Líneas geométricas, ondas o figuras personalizadas ejecutadas a navaja sobre fade bajo o medio.',
    tags: ['Diseño', 'Freestyle', 'Arte', 'Navaja', 'Personalizado'],
    previewOverlayUrl: '/lookbook/look_19.jpg',
    difficultyLevel: 'avanzado',
    hairType: 'todos',
    faceShape: 'Personalización exclusiva según gusto del cliente.',
    technicalFormula: 'Trazado con trimmer de precisión • Afeitado con navaja y gel transparente',
    angles: { front: '/lookbook/look_19.jpg', side: '/lookbook/look_19.jpg', back: '/lookbook/look_19.jpg' }
  }
];

export const LOOKBOOK_GALLERY_ITEMS: LookbookItem[] = [];

