// ==========================================================================
// BARBERIA_PRO - Biblioteca Visual de Estilos Oficial (Cabello & Barba)
// 44 Referencias Visuales Limpias con Rutas Estandarizadas
// ==========================================================================

export type StyleDomain = 'cabello' | 'barba' | 'combos';

export interface VisualStyleItem {
  id: string;
  domain: StyleDomain;
  name: string;
  category: string;
  categoryKey: string;
  description: string;
  duration: string;
  maintenance: string;
  thumbnail: string;
  image: string;
  technicalFormula?: string;
  faceShape?: string;
}

export const HAIR_CATEGORIES = [
  { key: 'todas', label: 'Todos los Cortes' },
  { key: 'fades', label: 'Fades & Degradados' },
  { key: 'taper', label: 'Taper & Clásicos' },
  { key: 'disenos', label: 'Diseños & Freestyle' },
  { key: 'modernos', label: 'Modernos & Textura' },
] as const;

export const BEARD_CATEGORIES = [
  { key: 'todas', label: 'Todas las Barbas' },
  { key: 'cortas', label: 'Cortas & Stubble' },
  { key: 'perfiladas', label: 'Perfiladas & Balbo / Van Dyke' },
  { key: 'completas', label: 'Completas & Groomed' },
] as const;

export const COMBO_CATEGORIES = [
  { key: 'todas', label: 'Todos los Combos' },
  { key: 'corte_barba', label: 'Corte + Barba' },
  { key: 'corte_cejas', label: 'Corte + Cejas' },
  { key: 'corte_ritual', label: 'Corte + Ritual Barboterapia' },
] as const;


export const OFFICIAL_STYLES_LIBRARY: VisualStyleItem[] = [
  // =========================================================================
  // ✂️ ESTILOS DE CABELLO
  // =========================================================================
  {
    id: 'hair_01',
    domain: 'cabello',
    name: 'Taper Fade Clásico Pro',
    category: 'Taper & Clásicos',
    categoryKey: 'taper',
    description: 'Desvanecido bajo y limpio en patillas y nuca con caída natural en cúspide.',
    duration: '35–45 min',
    maintenance: '2 semanas',
    thumbnail: '/styles/hair_01.jpg',
    image: '/styles/hair_01.jpg',
    technicalFormula: 'Taper 0.5 a 2 en sienes • Corte a tijera superior 4cm',
    faceShape: 'Universal, estiliza todo tipo de rostro.',
  },
  {
    id: 'hair_02',
    domain: 'cabello',
    name: 'Taper Fade Urbano Texturizado',
    category: 'Taper & Clásicos',
    categoryKey: 'taper',
    description: 'Conexión suave en laterales con textura superior mate y acabado natural.',
    duration: '40–50 min',
    maintenance: '2–3 semanas',
    thumbnail: '/styles/hair_02.jpg',
    image: '/styles/hair_02.jpg',
    technicalFormula: 'Laterales en tijera sobre peine y desvanecido en nuca',
    faceShape: 'Ideal para perfiles juveniles y ejecutivos.',
  },
  {
    id: 'hair_03',
    domain: 'cabello',
    name: 'Low Taper Fade Definido',
    category: 'Taper & Clásicos',
    categoryKey: 'taper',
    description: 'Perfilado ultra nítido en contornos con degradado bajo que conserva densidad.',
    duration: '35–45 min',
    maintenance: '2 semanas',
    thumbnail: '/styles/hair_03.jpg',
    image: '/styles/hair_03.jpg',
    technicalFormula: 'Guía 0 en patilla • Navaja en contornos • Textura en puntas',
    faceShape: 'Favorece rostros ovalados y cuadrados.',
  },
  {
    id: 'hair_04',
    domain: 'cabello',
    name: 'High Top Fade Estructurado',
    category: 'Fades & Degradados',
    categoryKey: 'fades',
    description: 'Degradado alto al ras con volumen y estructura superior definida.',
    duration: '45–55 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/hair_04.jpg',
    image: '/styles/hair_04.jpg',
    technicalFormula: 'Skin fade alto desde 0 a 1.5 • Esculpido superior con peine plano',
    faceShape: 'Aporta altura y presencia en rostros redondos.',
  },
  {
    id: 'hair_05',
    domain: 'cabello',
    name: 'High Fade con Corona Definida',
    category: 'Fades & Degradados',
    categoryKey: 'fades',
    description: 'Transición limpia a piel conectando con cúspide densa y perfilado frontal.',
    duration: '40–50 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/hair_05.jpg',
    image: '/styles/hair_05.jpg',
    technicalFormula: 'Cuchilla plana en base • Fade intermedio 1 a 2 • Trimmer en frentes',
    faceShape: 'Excelente para facciones marcadas.',
  },
  {
    id: 'hair_06',
    domain: 'cabello',
    name: 'High Fade Texturizado Afro / Rizo',
    category: 'Fades & Degradados',
    categoryKey: 'fades',
    description: 'Degradado alto pulido con esponja definidora de rizos en parte superior.',
    duration: '45–55 min',
    maintenance: '2 semanas',
    thumbnail: '/styles/hair_06.jpg',
    image: '/styles/hair_06.jpg',
    technicalFormula: 'Fade 0 a 1.5 • Hidratación con crema y esponja twist',
    faceShape: 'Destaca facciones masculinas y volumen facial.',
  },
  {
    id: 'hair_07',
    domain: 'cabello',
    name: 'High Top Fade Moderno',
    category: 'Fades & Degradados',
    categoryKey: 'fades',
    description: 'Corte de alto impacto con laterales a navaja y parte alta equilibrada.',
    duration: '40–50 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/hair_07.jpg',
    image: '/styles/hair_07.jpg',
    technicalFormula: 'Navaja en laterales • Tijera de entresacar en corona',
    faceShape: 'Estiliza mandíbulas anchas.',
  },
  {
    id: 'hair_08',
    domain: 'cabello',
    name: 'Mid-High Skin Fade Pro',
    category: 'Fades & Degradados',
    categoryKey: 'fades',
    description: 'Degradado medio-alto con sombras suaves y perfilado simétrico.',
    duration: '40–50 min',
    maintenance: '2 semanas',
    thumbnail: '/styles/hair_08.jpg',
    image: '/styles/hair_08.jpg',
    technicalFormula: 'Guías 0, 0.5, 1, 1.5 con palanca en juego • Tijera recta arriba',
    faceShape: 'Ideal para cualquier tipo de fisonomía.',
  },
  {
    id: 'hair_09',
    domain: 'cabello',
    name: 'Drop Fade Alto Urbano',
    category: 'Fades & Degradados',
    categoryKey: 'fades',
    description: 'Caída curva detrás de la oreja con fade progresivo y volumen central.',
    duration: '45–55 min',
    maintenance: '2 semanas',
    thumbnail: '/styles/hair_09.jpg',
    image: '/styles/hair_09.jpg',
    technicalFormula: 'Drop fade curvo hacia nuca • Textura desfilada en cúspide',
    faceShape: 'Realza la forma del cráneo y estiliza el cuello.',
  },
  {
    id: 'hair_10',
    domain: 'cabello',
    name: 'Clean Skin Fade & Razor Line',
    category: 'Fades & Degradados',
    categoryKey: 'fades',
    description: 'Fade afeitado con navaja en contornos y parte alta perfilada con precisión.',
    duration: '40–50 min',
    maintenance: '1 semana',
    thumbnail: '/styles/hair_10.jpg',
    image: '/styles/hair_10.jpg',
    technicalFormula: 'Shaver en base • Conexión milimétrica • Perfilado con gel frío',
    faceShape: 'Especial para perfiles deportivos y definidos.',
  },
  {
    id: 'hair_11',
    domain: 'cabello',
    name: 'Modern Curtains / Raya al Medio',
    category: 'Modernos & Textura',
    categoryKey: 'modernos',
    description: 'Estilo noventero moderno con caída libre de cabello a los lados y movimiento.',
    duration: '35–45 min',
    maintenance: '3–4 semanas',
    thumbnail: '/styles/hair_11.jpg',
    image: '/styles/hair_11.jpg',
    technicalFormula: 'Corte a tijera en capas con desfilado de puntas y secado con cepillo',
    faceShape: 'Suaviza rostros angulares y frentes amplias.',
  },
  {
    id: 'hair_12',
    domain: 'cabello',
    name: 'Curtains con Taper Fade Suave',
    category: 'Modernos & Textura',
    categoryKey: 'modernos',
    description: 'Combinación de textura superior en cortina con patillas desvanecidas.',
    duration: '40–50 min',
    maintenance: '3 semanas',
    thumbnail: '/styles/hair_12.jpg',
    image: '/styles/hair_12.jpg',
    technicalFormula: 'Taper bajo en orejas • Longitud 8 a 10cm en cúspide con movimiento',
    faceShape: 'Estilo versátil y muy juvenil.',
  },
  {
    id: 'hair_13',
    domain: 'cabello',
    name: 'Middle Part Texturizado Mate',
    category: 'Modernos & Textura',
    categoryKey: 'modernos',
    description: 'Partición central con fijación natural mate y volumen en raíces.',
    duration: '35–45 min',
    maintenance: '3–4 semanas',
    thumbnail: '/styles/hair_13.jpg',
    image: '/styles/hair_13.jpg',
    technicalFormula: 'Tijera de esculpir para quitar peso • Polvo texturizador mate',
    faceShape: 'Armoniza rostros rectangulares y ovalados.',
  },
  {
    id: 'hair_14',
    domain: 'cabello',
    name: 'Diseño Artístico en Nuca Freestyle',
    category: 'Diseños & Freestyle',
    categoryKey: 'disenos',
    description: 'Trazos geométricos y líneas de precisión ejecutadas a navaja sobre fade en nuca.',
    duration: '45–60 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/hair_14.jpg',
    image: '/styles/hair_14.jpg',
    technicalFormula: 'Trimmer de precisión para contornos • Navaja libre y gel transparente',
    faceShape: 'Personalización de impacto visual.',
  },
  {
    id: 'hair_15',
    domain: 'cabello',
    name: 'Corte Shaved con Líneas Freestyle',
    category: 'Diseños & Freestyle',
    categoryKey: 'disenos',
    description: 'Rapado lateral pulido con figuras grabadas a navaja y contraste superior.',
    duration: '40–55 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/hair_15.jpg',
    image: '/styles/hair_15.jpg',
    technicalFormula: 'Base 0.5 • Trimmer con grabado de patrones geométricos',
    faceShape: 'Máxima actitud y estilo urbano.',
  },
  {
    id: 'hair_16',
    domain: 'cabello',
    name: 'Diseño Geométrico Arrow / Flecha',
    category: 'Diseños & Freestyle',
    categoryKey: 'disenos',
    description: 'Patrones direccionales de flechas en degradado lateral con sombra.',
    duration: '45–60 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/hair_16.jpg',
    image: '/styles/hair_16.jpg',
    technicalFormula: 'Líneas paralelas a navaja sobre base en sombra de 1.0',
    faceShape: 'Estilo dinámico y moderno.',
  },
  {
    id: 'hair_17',
    domain: 'cabello',
    name: 'Diseño Star Burst Lateral',
    category: 'Diseños & Freestyle',
    categoryKey: 'disenos',
    description: 'Estrella trazada en relieve sobre fade medio con perfilado a navaja.',
    duration: '45–60 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/hair_17.jpg',
    image: '/styles/hair_17.jpg',
    technicalFormula: 'Marcación de puntas con trimmer • Afeitado interno con navaja',
    faceShape: 'Diseño favorito para niños y jóvenes.',
  },
  {
    id: 'hair_18',
    domain: 'cabello',
    name: 'Star Fade Freestyle Pro',
    category: 'Diseños & Freestyle',
    categoryKey: 'disenos',
    description: 'Integración de figura estelar con transición suave de fade a piel.',
    duration: '45–60 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/hair_18.jpg',
    image: '/styles/hair_18.jpg',
    technicalFormula: 'Grabado sobre piel con relieve en degradado',
    faceShape: 'Impacto visual único.',
  },
  {
    id: 'hair_19',
    domain: 'cabello',
    name: 'Diseño Diamante Geométrico',
    category: 'Diseños & Freestyle',
    categoryKey: 'disenos',
    description: 'Faceteado geométrico en forma de diamante tallado en laterales.',
    duration: '50–60 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/hair_19.jpg',
    image: '/styles/hair_19.jpg',
    technicalFormula: 'Trazado simétrico de ángulos con regla de visagismo y trimmer',
    faceShape: 'Perfil vanguardista.',
  },
  {
    id: 'hair_20',
    domain: 'cabello',
    name: 'Diseño Pluma / Feather Artístico',
    category: 'Diseños & Freestyle',
    categoryKey: 'disenos',
    description: 'Silueta fluida de pluma grabada con degradado en los filamentos.',
    duration: '50–65 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/hair_20.jpg',
    image: '/styles/hair_20.jpg',
    technicalFormula: 'Trazos curvos finos con micro-navaja y sombras difuminadas',
    faceShape: 'Obra de arte en barbería.',
  },
  {
    id: 'hair_21',
    domain: 'cabello',
    name: 'Diseño Flame / Fuego Lateral',
    category: 'Diseños & Freestyle',
    categoryKey: 'disenos',
    description: 'Llamas estilizadas en relieve sobre desvanecido a navaja.',
    duration: '50–65 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/hair_21.jpg',
    image: '/styles/hair_21.jpg',
    technicalFormula: 'Curvaturas de llama con navaja y contrastes de claro/oscuro',
    faceShape: 'Máxima expresión artística.',
  },
  {
    id: 'hair_22',
    domain: 'cabello',
    name: 'Lion Art Haircut Design',
    category: 'Diseños & Freestyle',
    categoryKey: 'disenos',
    description: 'Retrato de león esculpido en laterales con técnica de relieve y sombras.',
    duration: '60–75 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/hair_22.jpg',
    image: '/styles/hair_22.jpg',
    technicalFormula: 'Microsombras con guía 0.5 a 1.5 y navaja de precisión',
    faceShape: 'Nivel maestro de barbería artística.',
  },

  // =========================================================================
  // 🧔 ESTILOS DE BARBA
  // =========================================================================
  {
    id: 'beard_01',
    domain: 'barba',
    name: 'Barba tipo Balbo Esculpida',
    category: 'Perfiladas & Balbo / Van Dyke',
    categoryKey: 'perfiladas',
    description: 'Diseño elegante sin patillas, con bigote flotante recortado y perilla amplia.',
    duration: '35–45 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/beard_01.jpg',
    image: '/styles/beard_01.jpg',
    technicalFormula: 'Afeitado total de patillas • Perfilado a navaja en mentón y labio',
    faceShape: 'Alarga rostros redondos y resalta la mandíbula.',
  },
  {
    id: 'beard_02',
    domain: 'barba',
    name: 'Barba tipo Van Dyke Clásica',
    category: 'Perfiladas & Balbo / Van Dyke',
    categoryKey: 'perfiladas',
    description: 'Combinación icónica de perilla puntiaguda en barbilla y bigote definido desconectado.',
    duration: '30–40 min',
    maintenance: '1 semana',
    thumbnail: '/styles/beard_02.jpg',
    image: '/styles/beard_02.jpg',
    technicalFormula: 'Mejillas limpias a navaja • Fijación de puntas de bigote con cera',
    faceShape: 'Excelente para mentones prominentes y estilos distinguidos.',
  },
  {
    id: 'beard_03',
    domain: 'barba',
    name: 'Barba de Tres Días / Stubble Definida',
    category: 'Cortas & Stubble',
    categoryKey: 'cortas',
    description: 'Longitud sutil de 2mm a 4mm con líneas nítidas en cuello y pómulos.',
    duration: '20–25 min',
    maintenance: '3–5 días',
    thumbnail: '/styles/beard_03.jpg',
    image: '/styles/beard_03.jpg',
    technicalFormula: 'Guía 1.5 uniforme • Delimitación limpia a navaja en cuello a 2 dedos de nuez',
    faceShape: 'Universal, brinda aspecto masculino y prolijo.',
  },
  {
    id: 'beard_04',
    domain: 'barba',
    name: 'Heavy Stubble con Contornos Limpios',
    category: 'Cortas & Stubble',
    categoryKey: 'cortas',
    description: 'Sombra densa de 4mm a 5mm con perfilado suave en mejillas.',
    duration: '25–30 min',
    maintenance: '5–7 días',
    thumbnail: '/styles/beard_04.jpg',
    image: '/styles/beard_04.jpg',
    technicalFormula: 'Guía 2 con desvanecido leve en patilla • Navaja e hidratación',
    faceShape: 'Disimula imperfecciones y enmarca el rostro.',
  },
  {
    id: 'beard_05',
    domain: 'barba',
    name: 'Barba Completa Groomed & Boxed',
    category: 'Completas & Groomed',
    categoryKey: 'completas',
    description: 'Estructura uniforme con volumen denso, peinado con bálsamo y base cuadrada.',
    duration: '35–45 min',
    maintenance: '2 semanas',
    thumbnail: '/styles/beard_05.jpg',
    image: '/styles/beard_05.jpg',
    technicalFormula: 'Peinado con cepillo térmico • Tijera para puntas rebeldes • Aceite hidratante',
    faceShape: 'Aporta solidez a mandíbulas estrechas y rostros alargados.',
  },
  {
    id: 'beard_06',
    domain: 'barba',
    name: 'Barba Media Degradada al Fade',
    category: 'Completas & Groomed',
    categoryKey: 'completas',
    description: 'Transición milimétrica desde el corte de cabello hacia la densidad de la barba.',
    duration: '35–45 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/beard_06.jpg',
    image: '/styles/beard_06.jpg',
    technicalFormula: 'Fade inverso de 0.5 a 3 desde patilla • Perfilado superior a navaja',
    faceShape: 'Estiliza los pómulos y estiliza el perfil.',
  },
  {
    id: 'beard_07',
    domain: 'barba',
    name: 'Barba Perfilada Ejecutiva',
    category: 'Completas & Groomed',
    categoryKey: 'completas',
    description: 'Acabado de alta barbería con ritual de toalla caliente y simetría total.',
    duration: '40–50 min',
    maintenance: '2 semanas',
    thumbnail: '/styles/beard_07.jpg',
    image: '/styles/beard_07.jpg',
    technicalFormula: 'Toalla caliente • Navaja en ángulo de 30° • Masaje con tónico capilar',
    faceShape: 'Perfecta para eventos formales y oficina.',
  },

  // =========================================================================
  // 🔥 COMBOS & RITUALES
  // =========================================================================
  {
    id: 'combo_01',
    domain: 'combos',
    name: 'Combo Pro: Corte + Barba Perfilada',
    category: 'Corte + Barba',
    categoryKey: 'corte_barba',
    description: 'El combo estrella: Corte de cabello degradado o clásico con diseño y perfilado de barba a navaja.',
    duration: '55–65 min',
    maintenance: '2 semanas',
    thumbnail: '/styles/hair_01.jpg',
    image: '/styles/hair_01.jpg',
    technicalFormula: 'Fade personalizado + Perfilado de barba a navaja con toalla caliente',
    faceShape: 'Transformación visual completa para todo tipo de rostro.',
  },
  {
    id: 'combo_02',
    domain: 'combos',
    name: 'Combo Urbano: Corte + Cejas con Navaja',
    category: 'Corte + Cejas',
    categoryKey: 'corte_cejas',
    description: 'Degradado limpio o Mid Fade acompañado de limpieza y definición de cejas con navaja.',
    duration: '40–50 min',
    maintenance: '10–14 días',
    thumbnail: '/styles/hair_04.jpg',
    image: '/styles/hair_04.jpg',
    technicalFormula: 'Mid Fade a navaja + Limpieza simétrica de cejas sin perder naturalidad',
    faceShape: 'Resalta la mirada y define los rasgos faciales.',
  },
  {
    id: 'combo_03',
    domain: 'combos',
    name: 'Ritual Maestro: Corte + Barboterapia Spa',
    category: 'Corte + Ritual Barboterapia',
    categoryKey: 'corte_ritual',
    description: 'Experiencia premium completa: Corte, toalla vaporizada, exfoliación facial, perfilado y masaje relajante.',
    duration: '70–80 min',
    maintenance: '3 semanas',
    thumbnail: '/styles/hair_12.jpg',
    image: '/styles/hair_12.jpg',
    technicalFormula: 'Corte a tijera o máquina + Doble toalla vaporizada + Aceites esenciales y bálsamo',
    faceShape: 'La máxima experiencia de relajación y estilo para caballeros exigentes.',
  }
];

export type BeardStyle = VisualStyleItem;
export const OFFICIAL_BEARD_STYLES = OFFICIAL_STYLES_LIBRARY.filter(s => s.domain === 'barba');
export const OFFICIAL_HAIR_STYLES = OFFICIAL_STYLES_LIBRARY.filter(s => s.domain === 'cabello');
export const OFFICIAL_COMBO_STYLES = OFFICIAL_STYLES_LIBRARY.filter(s => s.domain === 'combos');

