// ==========================================================================
// BARBERIA_PRO - Biblioteca Visual de Estilos Oficial (Cabello & Barba)
// 44 Referencias Visuales en 4:3 con Vistas y Fórmulas Técnicas
// ==========================================================================

export type StyleDomain = 'cabello' | 'barba';

export interface VisualStyleItem {
  id: string;
  domain: StyleDomain;
  name: string;
  category: string;
  categoryKey: string;
  description: string;
  duration: string;
  maintenance: string;
  thumbnail: string;
  image: string;
  technicalFormula?: string;
  faceShape?: string;
}

export const HAIR_CATEGORIES = [
  { key: 'todas', label: 'Todos los Cortes' },
  { key: 'fades', label: 'Fades & Degradados' },
  { key: 'taper', label: 'Taper & Clásicos' },
  { key: 'disenos', label: 'Diseños & Freestyle' },
  { key: 'modernos', label: 'Modernos & Textura' },
] as const;

export const BEARD_CATEGORIES = [
  { key: 'todas', label: 'Todas las Barbas' },
  { key: 'cortas', label: 'Cortas & Stubble' },
  { key: 'perfiladas', label: 'Perfiladas & Balbo / Van Dyke' },
  { key: 'completas', label: 'Completas & Groomed' },
  { key: 'catalogo', label: 'Colección 3D / Pro' },
] as const;

export const OFFICIAL_STYLES_LIBRARY: VisualStyleItem[] = [
  // =========================================================================
  // ✂️ ESTILOS DE CABELLO (HAIRCUTS & DESIGNS)
  // =========================================================================
  {
    id: 'hair_taper_fade_01',
    domain: 'cabello',
    name: 'Taper Fade Clásico Pro',
    category: 'Taper & Clásicos',
    categoryKey: 'taper',
    description: 'Desvanecido bajo y limpio en patillas y nuca con caída natural en cúspide.',
    duration: '35–45 min',
    maintenance: '2 semanas',
    thumbnail: '/styles/Men_showcasing_taper_fade_haircut_202608201950.jpeg',
    image: '/styles/Men_showcasing_taper_fade_haircut_202608201950.jpeg',
    technicalFormula: 'Taper 0.5 a 2 en sienes • Corte a tijera superior 4cm',
    faceShape: 'Universal, estiliza todo tipo de rostro.',
  },
  {
    id: 'hair_taper_fade_02',
    domain: 'cabello',
    name: 'Taper Fade Urbano Texturizado',
    category: 'Taper & Clásicos',
    categoryKey: 'taper',
    description: 'Conexión suave en laterales con textura superior mate y acabado natural.',
    duration: '40–50 min',
    maintenance: '2–3 semanas',
    thumbnail: '/styles/Men_showcasing_taper_fade_haircut_202608201954.jpeg',
    image: '/styles/Men_showcasing_taper_fade_haircut_202608201954.jpeg',
    technicalFormula: 'Laterales en tijera sobre peine y desvanecido en nuca',
    faceShape: 'Ideal para perfiles juveniles y ejecutivos.',
  },
  {
    id: 'hair_taper_fade_03',
    domain: 'cabello',
    name: 'Low Taper Fade Definido',
    category: 'Taper & Clásicos',
    categoryKey: 'taper',
    description: 'Perfilado ultra nítido en contornos con degradado bajo que conserva densidad.',
    duration: '35–45 min',
    maintenance: '2 semanas',
    thumbnail: '/styles/Men_showcasing_taper_fade_haircut_202608201956.jpeg',
    image: '/styles/Men_showcasing_taper_fade_haircut_202608201956.jpeg',
    technicalFormula: 'Guía 0 en patilla • Navaja en contornos • Textura en puntas',
    faceShape: 'Favorece rostros ovalados y cuadrados.',
  },
  {
    id: 'hair_high_top_01',
    domain: 'cabello',
    name: 'High Top Fade Estructurado',
    category: 'Fades & Degradados',
    categoryKey: 'fades',
    description: 'Degradado alto al ras con volumen y estructura superior definida.',
    duration: '45–55 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/Man_displaying_high_top_fade_202608202011.jpeg',
    image: '/styles/Man_displaying_high_top_fade_202608202011.jpeg',
    technicalFormula: 'Skin fade alto desde 0 a 1.5 • Esculpido superior con peine plano',
    faceShape: 'Aporta altura y presencia en rostros redondos.',
  },
  {
    id: 'hair_high_top_02',
    domain: 'cabello',
    name: 'High Fade con Corona Definida',
    category: 'Fades & Degradados',
    categoryKey: 'fades',
    description: 'Transición limpia a piel conectando con cúspide densa y perfilado frontal.',
    duration: '40–50 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/Man_displaying_high_top_fade_202608202013.jpeg',
    image: '/styles/Man_displaying_high_top_fade_202608202013.jpeg',
    technicalFormula: 'Cuchilla plana en base • Fade intermedio 1 a 2 • Trimmer en frentes',
    faceShape: 'Excelente para facciones marcadas.',
  },
  {
    id: 'hair_high_top_03',
    domain: 'cabello',
    name: 'High Fade Texturizado Afro / Rizo',
    category: 'Fades & Degradados',
    categoryKey: 'fades',
    description: 'Degradado alto pulido con esponja definidora de rizos en parte superior.',
    duration: '45–55 min',
    maintenance: '2 semanas',
    thumbnail: '/styles/Man_displaying_high_top_fade_202608202014.jpeg',
    image: '/styles/Man_displaying_high_top_fade_202608202014.jpeg',
    technicalFormula: 'Fade 0 a 1.5 • Hidratación con crema y esponja twist',
    faceShape: 'Destaca facciones masculinas y volumen facial.',
  },
  {
    id: 'hair_high_top_04',
    domain: 'cabello',
    name: 'High Top Fade Moderno',
    category: 'Fades & Degradados',
    categoryKey: 'fades',
    description: 'Corte de alto impacto con laterales a navaja y parte alta equilibrada.',
    duration: '40–50 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/Man_displaying_high_top_fade_202608202016.jpeg',
    image: '/styles/Man_displaying_high_top_fade_202608202016.jpeg',
    technicalFormula: 'Navaja en laterales • Tijera de entresacar en corona',
    faceShape: 'Estiliza mandíbulas anchas.',
  },
  {
    id: 'hair_high_top_05',
    domain: 'cabello',
    name: 'Mid-High Skin Fade Pro',
    category: 'Fades & Degradados',
    categoryKey: 'fades',
    description: 'Degradado medio-alto con sombras suaves y perfilado simétrico.',
    duration: '40–50 min',
    maintenance: '2 semanas',
    thumbnail: '/styles/Man_displaying_high_top_fade_202608202018.jpeg',
    image: '/styles/Man_displaying_high_top_fade_202608202018.jpeg',
    technicalFormula: 'Guías 0, 0.5, 1, 1.5 con palanca en juego • Tijera recta arriba',
    faceShape: 'Ideal para cualquier tipo de fisonomía.',
  },
  {
    id: 'hair_high_top_06',
    domain: 'cabello',
    name: 'Drop Fade Alto Urbano',
    category: 'Fades & Degradados',
    categoryKey: 'fades',
    description: 'Caída curva detrás de la oreja con fade progresivo y volumen central.',
    duration: '45–55 min',
    maintenance: '2 semanas',
    thumbnail: '/styles/Man_displaying_high_top_fade_202608202019.jpeg',
    image: '/styles/Man_displaying_high_top_fade_202608202019.jpeg',
    technicalFormula: 'Drop fade curvo hacia nuca • Textura desfilada en cúspide',
    faceShape: 'Realza la forma del cráneo y estiliza el cuello.',
  },
  {
    id: 'hair_high_top_07',
    domain: 'cabello',
    name: 'Clean Skin Fade & Razor Line',
    category: 'Fades & Degradados',
    categoryKey: 'fades',
    description: 'Fade afeitado con navaja en contornos y parte alta perfilada con precisión.',
    duration: '40–50 min',
    maintenance: '1 semana',
    thumbnail: '/styles/Man_displaying_high_top_fade_202608202020.jpeg',
    image: '/styles/Man_displaying_high_top_fade_202608202020.jpeg',
    technicalFormula: 'Shaver en base • Conexión milimétrica • Perfilado con gel frío',
    faceShape: 'Especial para perfiles deportivos y definidos.',
  },
  {
    id: 'hair_curtains_01',
    domain: 'cabello',
    name: 'Modern Curtains / Raya al Medio',
    category: 'Modernos & Textura',
    categoryKey: 'modernos',
    description: 'Estilo noventero moderno con caída libre de cabello a los lados y movimiento.',
    duration: '35–45 min',
    maintenance: '3–4 semanas',
    thumbnail: '/styles/Man_wearing_modern_curtains_haircut_202608202006.jpeg',
    image: '/styles/Man_wearing_modern_curtains_haircut_202608202006.jpeg',
    technicalFormula: 'Corte a tijera en capas con desfilado de puntas y secado con cepillo',
    faceShape: 'Suaviza rostros angulares y frentes amplias.',
  },
  {
    id: 'hair_curtains_02',
    domain: 'cabello',
    name: 'Curtains con Taper Fade Suave',
    category: 'Modernos & Textura',
    categoryKey: 'modernos',
    description: 'Combinación de textura superior en cortina con patillas desvanecidas.',
    duration: '40–50 min',
    maintenance: '3 semanas',
    thumbnail: '/styles/Man_wearing_modern_curtains_haircut_202608202007.jpeg',
    image: '/styles/Man_wearing_modern_curtains_haircut_202608202007.jpeg',
    technicalFormula: 'Taper bajo en orejas • Longitud 8 a 10cm en cúspide con movimiento',
    faceShape: 'Estilo versátil y muy juvenil.',
  },
  {
    id: 'hair_curtains_03',
    domain: 'cabello',
    name: 'Middle Part Texturizado Mate',
    category: 'Modernos & Textura',
    categoryKey: 'modernos',
    description: 'Partición central con fijación natural mate y volumen en raíces.',
    duration: '35–45 min',
    maintenance: '3–4 semanas',
    thumbnail: '/styles/Man_wearing_modern_curtains_haircut_202608202009.jpeg',
    image: '/styles/Man_wearing_modern_curtains_haircut_202608202009.jpeg',
    technicalFormula: 'Tijera de esculpir para quitar peso • Polvo texturizador mate',
    faceShape: 'Armoniza rostros rectangulares y ovalados.',
  },
  {
    id: 'hair_design_nape',
    domain: 'cabello',
    name: 'Diseño Artístico en Nuca Freestyle',
    category: 'Diseños & Freestyle',
    categoryKey: 'disenos',
    description: 'Trazos geométricos y líneas de precisión ejecutadas a navaja sobre fade en nuca.',
    duration: '45–60 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/Man_displaying_nape_haircut_design_202608202024.jpeg',
    image: '/styles/Man_displaying_nape_haircut_design_202608202024.jpeg',
    technicalFormula: 'Trimmer de precisión para contornos • Navaja libre y gel transparente',
    faceShape: 'Personalización de impacto visual.',
  },
  {
    id: 'hair_design_shaved',
    domain: 'cabello',
    name: 'Corte Shaved con Líneas Freestyle',
    category: 'Diseños & Freestyle',
    categoryKey: 'disenos',
    description: 'Rapado lateral pulido con figuras grabadas a navaja y contraste superior.',
    duration: '40–55 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/Man_with_shaved_haircut_202608202022.jpeg',
    image: '/styles/Man_with_shaved_haircut_202608202022.jpeg',
    technicalFormula: 'Base 0.5 • Trimmer con grabado de patrones geométricos',
    faceShape: 'Máxima actitud y estilo urbano.',
  },
  {
    id: 'hair_design_arrow',
    domain: 'cabello',
    name: 'Diseño Geométrico Arrow / Flecha',
    category: 'Diseños & Freestyle',
    categoryKey: 'disenos',
    description: 'Patrones direccionales de flechas en degradado lateral con sombra.',
    duration: '45–60 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/Man_with_geometric_arrow_haircut_202608202026.jpeg',
    image: '/styles/Man_with_geometric_arrow_haircut_202608202026.jpeg',
    technicalFormula: 'Líneas paralelas a navaja sobre base en sombra de 1.0',
    faceShape: 'Estilo dinámico y moderno.',
  },
  {
    id: 'hair_design_star_01',
    domain: 'cabello',
    name: 'Diseño Star Burst Lateral',
    category: 'Diseños & Freestyle',
    categoryKey: 'disenos',
    description: 'Estrella trazada en relieve sobre fade medio con perfilado a navaja.',
    duration: '45–60 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/Man_with_star_haircut_design_202608202027.jpeg',
    image: '/styles/Man_with_star_haircut_design_202608202027.jpeg',
    technicalFormula: 'Marcación de puntas con trimmer • Afeitado interno con navaja',
    faceShape: 'Diseño favorito para niños y jóvenes.',
  },
  {
    id: 'hair_design_star_02',
    domain: 'cabello',
    name: 'Star Fade Freestyle Pro',
    category: 'Diseños & Freestyle',
    categoryKey: 'disenos',
    description: 'Integración de figura estelar con transición suave de fade a piel.',
    duration: '45–60 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/Man_with_star_haircut_design_202608202029.jpeg',
    image: '/styles/Man_with_star_haircut_design_202608202029.jpeg',
    technicalFormula: 'Grabado sobre piel con relieve en degradado',
    faceShape: 'Impacto visual único.',
  },
  {
    id: 'hair_design_diamond',
    domain: 'cabello',
    name: 'Diseño Diamante Geométrico',
    category: 'Diseños & Freestyle',
    categoryKey: 'disenos',
    description: 'Faceteado geométrico en forma de diamante tallado en laterales.',
    duration: '50–60 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/Man_modeling_diamond_haircut_202608202040.jpeg',
    image: '/styles/Man_modeling_diamond_haircut_202608202040.jpeg',
    technicalFormula: 'Trazado simétrico de ángulos con regla de visagismo y trimmer',
    faceShape: 'Perfil vanguardista.',
  },
  {
    id: 'hair_design_feather',
    domain: 'cabello',
    name: 'Diseño Pluma / Feather Artístico',
    category: 'Diseños & Freestyle',
    categoryKey: 'disenos',
    description: 'Silueta fluida de pluma grabada con degradado en los filamentos.',
    duration: '50–65 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/Man_modeling_shaved_feather_haircut_202608202043.jpeg',
    image: '/styles/Man_modeling_shaved_feather_haircut_202608202043.jpeg',
    technicalFormula: 'Trazos curvos finos con micro-navaja y sombras difuminadas',
    faceShape: 'Obra de arte en barbería.',
  },
  {
    id: 'hair_design_flame',
    domain: 'cabello',
    name: 'Diseño Flame / Fuego Lateral',
    category: 'Diseños & Freestyle',
    categoryKey: 'disenos',
    description: 'Llamas estilizadas en relieve sobre desvanecido a navaja.',
    duration: '50–65 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/Man_showing_flame_shaved_hairstyle_202608202038.jpeg',
    image: '/styles/Man_showing_flame_shaved_hairstyle_202608202038.jpeg',
    technicalFormula: 'Curvaturas de llama con navaja y contrastes de claro/oscuro',
    faceShape: 'Máxima expresión artística.',
  },
  {
    id: 'hair_design_lion_01',
    domain: 'cabello',
    name: 'Lion Art Haircut Design',
    category: 'Diseños & Freestyle',
    categoryKey: 'disenos',
    description: 'Retrato de león esculpido en laterales con técnica de relieve y sombras.',
    duration: '60–75 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/Man_with_lion_haircut_design_202608202046.jpeg',
    image: '/styles/Man_with_lion_haircut_design_202608202046.jpeg',
    technicalFormula: 'Microsombras con guía 0.5 a 1.5 y navaja de precisión',
    faceShape: 'Nivel maestro de barbería artística.',
  },
  {
    id: 'hair_catalog_overview_01',
    domain: 'cabello',
    name: 'Colección de Cortes Urbanos 2026',
    category: 'Modernos & Textura',
    categoryKey: 'modernos',
    description: 'Muestra completa de estilos modernos, pompadour, crop y fades.',
    duration: '40–50 min',
    maintenance: '2–3 semanas',
    thumbnail: '/styles/Men_presenting_haircut_catalog_202608201944.jpeg',
    image: '/styles/Men_presenting_haircut_catalog_202608201944.jpeg',
    technicalFormula: 'Combinaciones oficiales de máquina y tijera',
    faceShape: 'Variedad adaptable a cada tipo de rostro.',
  },
  {
    id: 'hair_catalog_overview_02',
    domain: 'cabello',
    name: 'Catálogo Visual de Tendencias Pro',
    category: 'Modernos & Textura',
    categoryKey: 'modernos',
    description: 'Referencias visuales de cortes contemporáneos y degradados limpios.',
    duration: '40–50 min',
    maintenance: '2–3 semanas',
    thumbnail: '/styles/Men_presenting_haircut_catalog_202608201947.jpeg',
    image: '/styles/Men_presenting_haircut_catalog_202608201947.jpeg',
    technicalFormula: 'Técnicas de barbería clásica y urbana integradas',
    faceShape: 'Ideal para inspirar tu próximo cambio de look.',
  },

  // =========================================================================
  // 🧔 ESTILOS DE BARBA (BEARD STYLES & GROOMING)
  // =========================================================================
  {
    id: 'beard_balbo_01',
    domain: 'barba',
    name: 'Barba tipo Balbo Esculpida',
    category: 'Perfiladas & Balbo / Van Dyke',
    categoryKey: 'perfiladas',
    description: 'Diseño elegante sin patillas, con bigote flotante recortado y perilla amplia.',
    duration: '35–45 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/Man_modeling_Balbo_beard_portrait_202608202054.jpeg',
    image: '/styles/Man_modeling_Balbo_beard_portrait_202608202054.jpeg',
    technicalFormula: 'Afeitado total de patillas • Perfilado a navaja en mentón y labio',
    faceShape: 'Alarga rostros redondos y resalta la mandíbula.',
  },
  {
    id: 'beard_van_dyke_01',
    domain: 'barba',
    name: 'Barba tipo Van Dyke Clásica',
    category: 'Perfiladas & Balbo / Van Dyke',
    categoryKey: 'perfiladas',
    description: 'Combinación icónica de perilla puntiaguda en barbilla y bigote definido desconectado.',
    duration: '30–40 min',
    maintenance: '1 semana',
    thumbnail: '/styles/Man_with_Van_Dyke_beard_202608202055.jpeg',
    image: '/styles/Man_with_Van_Dyke_beard_202608202055.jpeg',
    technicalFormula: 'Mejillas limpias a navaja • Fijación de puntas de bigote con cera',
    faceShape: 'Excelente para mentones prominentes y estilos distinguidos.',
  },
  {
    id: 'beard_stubble_01',
    domain: 'barba',
    name: 'Barba de Tres Días / Stubble Definida',
    category: 'Cortas & Stubble',
    categoryKey: 'cortas',
    description: 'Longitud sutil de 2mm a 4mm con líneas nítidas en cuello y pómulos.',
    duration: '20–25 min',
    maintenance: '3–5 días',
    thumbnail: '/styles/Man_with_stubble_beard_202608202059.jpeg',
    image: '/styles/Man_with_stubble_beard_202608202059.jpeg',
    technicalFormula: 'Guía 1.5 uniforme • Delimitación limpia a navaja en cuello a 2 dedos de nuez',
    faceShape: 'Universal, brinda aspecto masculino y prolijo.',
  },
  {
    id: 'beard_stubble_02',
    domain: 'barba',
    name: 'Heavy Stubble con Contornos Limpios',
    category: 'Cortas & Stubble',
    categoryKey: 'cortas',
    description: 'Sombra densa de 4mm a 5mm con perfilado suave en mejillas.',
    duration: '25–30 min',
    maintenance: '5–7 días',
    thumbnail: '/styles/Man_with_stubble_beard_202608202100.jpeg',
    image: '/styles/Man_with_stubble_beard_202608202100.jpeg',
    technicalFormula: 'Guía 2 con desvanecido leve en patilla • Navaja e hidratación',
    faceShape: 'Disimula imperfecciones y enmarca el rostro.',
  },
  {
    id: 'beard_groomed_01',
    domain: 'barba',
    name: 'Barba Completa Groomed & Boxed',
    category: 'Completas & Groomed',
    categoryKey: 'completas',
    description: 'Estructura uniforme con volumen denso, peinado con bálsamo y base cuadrada.',
    duration: '35–45 min',
    maintenance: '2 semanas',
    thumbnail: '/styles/Man_modeling_groomed_beard_202608202052.jpeg',
    image: '/styles/Man_modeling_groomed_beard_202608202052.jpeg',
    technicalFormula: 'Peinado con cepillo térmico • Tijera para puntas rebeldes • Aceite hidratante',
    faceShape: 'Aporta solidez a mandíbulas estrechas y rostros alargados.',
  },
  {
    id: 'beard_style_01',
    domain: 'barba',
    name: 'Barba Media Degradada al Fade',
    category: 'Completas & Groomed',
    categoryKey: 'completas',
    description: 'Transición milimétrica desde el corte de cabello hacia la densidad de la barba.',
    duration: '35–45 min',
    maintenance: '1–2 semanas',
    thumbnail: '/styles/Man_modeling_beard_style_202608202101.jpeg',
    image: '/styles/Man_modeling_beard_style_202608202101.jpeg',
    technicalFormula: 'Fade inverso de 0.5 a 3 desde patilla • Perfilado superior a navaja',
    faceShape: 'Estiliza los pómulos y estiliza el perfil.',
  },
  {
    id: 'beard_style_02',
    domain: 'barba',
    name: 'Barba Perfilada Ejecutiva',
    category: 'Completas & Groomed',
    categoryKey: 'completas',
    description: 'Acabado de alta barbería con ritual de toalla caliente y simetría total.',
    duration: '40–50 min',
    maintenance: '2 semanas',
    thumbnail: '/styles/Man_modeling_beard_style_202608202102.jpeg',
    image: '/styles/Man_modeling_beard_style_202608202102.jpeg',
    technicalFormula: 'Toalla caliente • Navaja en ángulo de 30° • Masaje con tónico capilar',
    faceShape: 'Perfecta para eventos formales y oficina.',
  },
  {
    id: 'beard_catalog_3d_01',
    domain: 'barba',
    name: 'Referencia 3D Barba Esculpida Pro',
    category: 'Colección 3D / Pro',
    categoryKey: 'catalogo',
    description: 'Modelo visual multiángulo para análisis de proporciones y visagismo.',
    duration: '35–45 min',
    maintenance: '2 semanas',
    thumbnail: '/styles/Barbershop_catalog_3D_model_202608201959.jpeg',
    image: '/styles/Barbershop_catalog_3D_model_202608201959.jpeg',
    technicalFormula: 'Modelado volumétrico en 3 planos (Frontal, Lateral, Perfil)',
    faceShape: 'Guía técnica para el barbero.',
  },
  {
    id: 'beard_catalog_3d_02',
    domain: 'barba',
    name: 'Colección Barba & Corte Sincronizado',
    category: 'Colección 3D / Pro',
    categoryKey: 'catalogo',
    description: 'Armonía integral entre corte de cabello desvanecido y barba estructurada.',
    duration: '50–60 min',
    maintenance: '2 semanas',
    thumbnail: '/styles/Barbershop_catalog_3D_model_202608202000.jpeg',
    image: '/styles/Barbershop_catalog_3D_model_202608202000.jpeg',
    technicalFormula: 'Corte completo combo Barba + Fade clásico',
    faceShape: 'Look integral completo de barbería.',
  },
  {
    id: 'beard_catalog_3d_03',
    domain: 'barba',
    name: 'Visagismo de Barba y Cuello Pro',
    category: 'Colección 3D / Pro',
    categoryKey: 'catalogo',
    description: 'Alineación anatómica para resaltar la estructura ósea mandibular.',
    duration: '35–45 min',
    maintenance: '2 semanas',
    thumbnail: '/styles/Barbershop_catalog_3D_model_202608202001.jpeg',
    image: '/styles/Barbershop_catalog_3D_model_202608202001.jpeg',
    technicalFormula: 'Trazado milimétrico de líneas faciales',
    faceShape: 'Recomendado para rostros redondos y asimétricos.',
  },
  {
    id: 'beard_catalog_3d_04',
    domain: 'barba',
    name: 'Barba Esculpida de Precisión 3D',
    category: 'Colección 3D / Pro',
    categoryKey: 'catalogo',
    description: 'Definición de contornos rectos y curvos con acabado pulido.',
    duration: '40–50 min',
    maintenance: '2 semanas',
    thumbnail: '/styles/Barbershop_catalog_3D_model_202608202002.jpeg',
    image: '/styles/Barbershop_catalog_3D_model_202608202002.jpeg',
    technicalFormula: 'Corte a navaja y máquina con peine guía especial',
    faceShape: 'Máxima nitidez visual.',
  },
  {
    id: 'beard_catalog_layout',
    domain: 'barba',
    name: 'Composición Editorial de Estilos de Barba',
    category: 'Colección 3D / Pro',
    categoryKey: 'catalogo',
    description: 'Catálogo con vistas completas de referencia para selección rápida en sillón.',
    duration: '35–45 min',
    maintenance: '2 semanas',
    thumbnail: '/styles/Barbershop_catalog_layout_creation_202608201948.jpeg',
    image: '/styles/Barbershop_catalog_layout_creation_202608201948.jpeg',
    technicalFormula: 'Guía de selección visual en sala de espera',
    faceShape: 'Ideal para mostrar al barbero antes de comenzar.',
  }
];

export type BeardStyle = VisualStyleItem;
export const OFFICIAL_BEARD_STYLES = OFFICIAL_STYLES_LIBRARY.filter(s => s.domain === 'barba');
export const OFFICIAL_HAIR_STYLES = OFFICIAL_STYLES_LIBRARY.filter(s => s.domain === 'cabello');
